title: Cesar's Ramirez CIT_481 Blog 1 2022

logo: /assets/img/AWS-EC2.png
description: A blog for Technology and tools for the CIT comunity
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
